import Header from "@/components/Header";
import "./globals.css";
import { ThemeProvider } from "@/clientSide";

export const metadata = {
  title: "Web25",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body suppressHydrationWarning={true} className="bg-white dark:bg-black">
        <ThemeProvider>
          <Header />

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
